### ISSUE TITLE
Add a link to the demo online

### ISSUE THREAD

**Issue by Haroenv** [nitin42/react-handy-renderer#1]
I could make it work on codesandbox by going to `/demo`, switching on module view and adding react as a dependency: https://codesandbox.io/s/github/nitin42/react-handy-renderer

**Comment by nitin42** [comment]
Are you sure it's working on your machine ? Because I couldn't get it to work !?

**Comment by Haroenv** [comment]
It only worked if I went to module view (the switch on the top right)

**Comment by nitin42** [comment]
Added the demo link! Thanks 😄
